CREATE TYPE scope AS ENUM ('FI', 'BRAND', 'EXTERNAL');

CREATE TYPE status AS ENUM ('ENABLED', 'DISABLED');

CREATE TYPE token_type AS ENUM ('INVITATION', 'RESET_PASSWORD', 'ACCESS', 'REFRESH');

CREATE TYPE token_status AS ENUM ('ACTIVE', 'REVOKED', 'EXPIRED');

CREATE TYPE user_status AS ENUM ('INVITED', 'ACTIVE', 'INACTIVE');

CREATE TYPE charge_fee_type AS ENUM ('INCLUSIVE', 'EXCLUSIVE');

CREATE TYPE fee_component_type AS ENUM ('FIXED', 'PERCENTAGE');

CREATE TYPE risk_type AS ENUM ('DEFAULT', 'CUSTOMER');

CREATE TYPE risk_action AS ENUM ('BLOCK', 'ALERT');

CREATE TYPE risk_duration AS ENUM ('HOUR', 'DAY', 'WEEK', 'MONTH');

CREATE TYPE routing_duration AS ENUM ('HOUR', 'DAY', 'WEEK', 'MONTH');

CREATE TYPE routing_type AS ENUM ('AMOUNT', 'PERCENTAGE', 'COUNT');

CREATE TYPE risk_customer_criteria_type AS ENUM ('TAG', 'ACCOUNT_TYPE');

CREATE TYPE psp_selection_mode AS ENUM ('PRIORITY', 'WEIGHTAGE');

CREATE TYPE webhook_status_type AS ENUM ('SUCCESS', 'FAILURE', 'NOTIFICATION');

CREATE TYPE transaction_status AS ENUM ('NEW', 'CREATED', 'INITIATED', 'PG_ACCEPTED', 'PG_REJECTED', 'REJECTED', 'PG_SUCCESS', 'PG_FAILED', 'SUCCESS', 'FAILED');

CREATE TYPE webhook_execution_status AS ENUM ('PENDING', 'IN_PROGRESS', 'SUCCESS', 'FAILED', 'RETRIED', 'CANCELLED');